#!/usr/bin/env bash

declare -r TASK_ROOT=$HOME/.todo/
declare -r TASK_FILE=$HOME/.todo/tasks

if [[ $# == 0 || ! $1 =~ init|list|add|mark ]]; then
  echo "Please run 'todo init|list|add|mark' command."
  exit 1
fi

if [[ $1 == 'init' ]]; then
  if [[ ! -d $TASK_ROOT ]]; then
      mkdir $TASK_ROOT
  fi
  if [[ ! -f $TASK_FILE ]]; then
      touch $TASK_FILE
  fi
  echo "Initialized successfully."
fi

if [[ ! -f $TASK_FILE ]]; then
  echo "Please run 'todo init' before running '<$1>' command."
  exit 1
fi

# task format: TBD 1 download paper ; DONE x2 buy pencil
if [[ $1 == 'list' ]]; then
  echo "# To be done"
  cat $TASK_FILE | grep -E '^[0-9]+ ' || echo "Empty"
  echo "# Completed"
  (cat $TASK_FILE | grep -E '^x[0-9]+ ' || echo "Empty") | sed -E 's/x//'
fi

if [[ $1 == 'add' ]]; then
  shift
  LAST_TASK_NUM=$(wc -l $TASK_FILE | cut -d' ' -f1)
  echo "$(($LAST_TASK_NUM + 1)) $@" >> $TASK_FILE
fi

if [[ $1 == 'mark' ]]; then
  shift
  del_task=$(echo $@ | sed -E 's/ /|/g')
  sed -i -E "s/^($del_task) /x&/" $TASK_FILE
fi
